### ISSUE TITLE
Getting connect time out  on running against cluster IP

### ISSUE THREAD

**Issue by Sree9120** [aerokube/moon#156]
I am able to run the scripts if i try against the external ip, somehow its not working in the cluster ip

**Comment by Sree9120** [comment]
[06:51:36] E/runner - Unable to start a WebDriver session.
(node:9) UnhandledPromiseRejectionWarning: Error: ETIMEDOUT connect ETIMEDOUT clusterIP:4444
    at ClientRequest.<anonymous> (/protractor/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[06:51:36] E/launcher - Error: Error: ETIMEDOUT connect ETIMEDOUT clusterIP:4444
    at ClientRequest.<anonymous> (/protractor/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[06:51:36] E/launcher - Process exited with error code 100

Note:- actual clusterip is mocked here

**Comment by aandryashin** [comment]
Is this permanent issue? Could you please try to use domain name instead ip
address?

ср, 7 авг. 2019 г., 10:00 Sreejith Rajagopal <notifications@github.com>:

**Comment by vania-pooh** [comment]
@Sree9120 shouldn't port 4444 be opened in firewall rules? Are you running everything in cloud platform or in Kubernetes on dedicated hardware?

**Comment by sujithgowda22** [comment]
@vania-pooh  Everything is running on AKS(Managed azure kubernetes service) Firewalls are all open

**Comment by aandryashin** [comment]
Please note that in cluster ip can be only accessed within cluster. Is
there LoadBbalancer? Could you please do
$ kubectl get svc -n moon

ср, 7 авг. 2019 г., 11:31 sujithgowda22 <notifications@github.com>:
