### ISSUE TITLE
Connection refused during changing of GKE settings

### ISSUE THREAD

**Issue by anthonybaldwin** [aerokube/moon#64]
Figured I'd see what you think about this... It could just be my fault.

Tests began failing to reach moon/selenoid, and appears to have happened due to sending a request to the hub immediately after changing the number of allowed k8 nodes w/in GKE settings. Is this a case of, "Duh. Don't do that, dummy."?

Either way, the fix for the connection error was to delete the moon pods (`kubectl delete po -l app=moon -n moon`). Also, even after deleting the stuck moon pods and stuck Chrome pods, the Chrome sessions still display via selenoid-ui.

```
2018/10/08 17:57:24 [INIT] [Guest access is supported as user "browsers"]
2018/10/08 17:58:09 [INIT] [S3 storage is not configured: content upload is unavailable]
2018/10/08 17:58:09 [INIT] [Using default Moon images: failed to fetch moon-config map: Get https://10.31.240.1:443/api/v1/namespaces/moon/configmaps/moon-config: dial tcp 10.31.240.1:443: connect: connection refused]
2018/10/08 17:58:09 [INIT] [Using aerokube/moon-video-recorder:latest image as videoRecorder]
2018/10/08 17:58:09 [INIT] [Using aerokube/defender:latest image as defender]
2018/10/08 17:58:09 [INIT] [Using aerokube/logger:latest image as logger]
2018/10/08 17:58:09 [INIT] [Listening on :4444]
2018/10/08 17:58:09 [INIT] [Found license for "xxx" allowing 50 simultaneous browser sessions (valid from 1970-01-01T00:00:00Z until 2019-03-01T00:00:00Z)]
2018/10/08 17:58:09 [INIT] [Failed to get required resource quota information: Get https://10.31.240.1:443/api/v1/namespaces/moon/resourcequotas: dial tcp 10.31.240.1:443: connect: connection refused. Please create such quota according to documentation.]
2018/10/08 17:58:09 [INIT] [Moon is now returning an error for all requests]
2018/10/08 18:05:02 [REQUEST_ERROR] [unknown] [10.128.0.4] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:05:05 [REQUEST_ERROR] [unknown] [10.128.0.9] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:05:07 [REQUEST_ERROR] [unknown] [10.128.0.9] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:15:02 [REQUEST_ERROR] [unknown] [10.128.0.9] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:15:03 [REQUEST_ERROR] [unknown] [10.28.14.1] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:15:05 [REQUEST_ERROR] [unknown] [10.128.0.6] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:15:07 [REQUEST_ERROR] [unknown] [10.128.0.8] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:25:03 [REQUEST_ERROR] [unknown] [10.128.0.9] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:25:06 [REQUEST_ERROR] [unknown] [10.128.0.8] [Rejecting user request because of invalid session quota configuration]
2018/10/08 18:25:07 [REQUEST_ERROR] [unknown] [10.128.0.6] [Rejecting user request because of invalid session quota configuration]
```

```
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: '17MB-21F-1089.local', ip: '172.29.17.95', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '1.8.0_161'
Driver info: driver.version: RemoteWebDriver

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at com.xxx.app.tools.TestBase.getChromeDriver(TestBase.java:237)
	at com.xxx.app.tools.TestBase.setupDriver(TestBase.java:103)
	at com.xxx.app.tools.TestBase._beforeClass(TestBase.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
	at okio.RealBufferedSink.write(RealBufferedSink.java:42)
	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
	at okio.ForwardingSink.write(ForwardingSink.java:35)
	at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
	at okio.RealBufferedSink.write(RealBufferedSink.java:92)
	at okhttp3.RequestBody$2.writeTo(RequestBody.java:98)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	... 30 more
```

**Comment by vania-pooh** [comment]
@anthonybaldwin Moon is checking whether license key is installed correctly by requesting resource quota information. The only limit you have to set correctly is maximum pods limit. Moon removes from this limit total number of pods running itself and checks whether this number corresponds to license key. Normally it should return an HTTP error (with status code) to every request when two numbers (actual and allowed number of pods) do not match. Getting broken pipe is a bug or misconfiguration.

Could you attach a screenshot - what exactly you changed in GKE settings?

**Comment by anthonybaldwin** [comment]
@vania-pooh Got it. I changed the max number of nodes here: https://goo.gl/AXBU6r

I will confirm this one more time for good measure when I have a chance to dive into the other issue I opened (regarding selectors). I'll try to get to it this evening or the next, and if not, this weekend.

**Comment by vania-pooh** [comment]
Closing because of inactivity. Feel free to reopen if having more questions.
