### ISSUE TITLE
Not specifying requests or limits in resource declaration is causing NPE

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#87]
Having the following `browsers.json`:
```
          "68.0": {
            "image": "selenoid/vnc_chrome:68.0",
            "port": "4444",
            "resources": {                              
              "limits": { //Only limits specified                               
                "cpu": "0.5",                             
                "memory": "512Mi"
              }
            }
          },
```
Getting NPE like the following:
```
2018/11/10 19:46:48 http: panic serving 192.168.65.3:55088: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc0000c2140)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0xf48100, 0x19a9d20)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
k8s.io/apimachinery/pkg/api/resource.(*Quantity).String(0x0, 0xc0000ae7dc, 0x4)
	/Users/vania-pooh/src/testing/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180103014849-68f9c3a1feb3/pkg/api/resource/quantity.go:610 +0x37
main.createSessionHandler.func1.1(0xc00023a400)
	/src/testing/moon/cmd/moon/moon.go:432 +0xfca
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc0003d4230, 0x11a1aa0, 0xc000200000, 0xc00023a300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/httputil/reverseproxy.go:197 +0x1de
main.createSessionHandler.func1(0x11a1aa0, 0xc000200000, 0xc00023a300)
	/src/testing/moon/cmd/moon/moon.go:605 +0x120
net/http.HandlerFunc.ServeHTTP(0x10d9b38, 0x11a1aa0, 0xc000200000, 0xc00023a300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
main.post.func1(0x11a1aa0, 0xc000200000, 0xc00023a300)
	/src/testing/moon/cmd/moon/moon.go:716 +0xa3
main.requireAuthOrGuest.func1(0x11a1aa0, 0xc000200000, 0xc00023a300)
	/src/testing/moon/cmd/moon/moon.go:724 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0000bd620, 0x11a1aa0, 0xc000200000, 0xc00023a300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0001e0840, 0x11a1aa0, 0xc000200000, 0xc00023a300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
github.com/aandryashin/moon/license.(*licenseBasedHandler).ServeHTTP(0xc0000b3920, 0x11a1aa0, 0xc000200000, 0xc00023a300)
```

**Comment by vania-pooh** [comment]
Fixed in aandryashin/moon#148.
